# Generated by Django 4.2.5 on 2023-10-06 18:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(max_length=40, verbose_name='Destino de parada')),
                ('origen', models.CharField(max_length=40, verbose_name='Origen de parada')),
                ('salida', models.DateTimeField(verbose_name='Momento de salida')),
                ('bus', models.CharField(max_length=50, verbose_name='Matricula del bus')),
                ('compannia', models.CharField(max_length=40, verbose_name='Compañia de viaje')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Targetas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreTargeta', models.CharField(max_length=50, verbose_name='Nombre de la targeta')),
                ('tipoTargeta', models.CharField(max_length=50, verbose_name='Tipo de targeta bancaria')),
                ('BancoTargeta', models.CharField(max_length=30, verbose_name='Banco de la targeta')),
                ('fechaVancimiento', models.DateField(verbose_name='Fecha de vencimiento')),
                ('contraseñaTargeta', models.CharField(max_length=50, verbose_name='Contraseña de la targeta')),
                ('duenno', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Dueño de la targeta')),
            ],
        ),
    ]
