# Generated by Django 4.2.5 on 2023-10-08 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_remove_targetas_contraseñatargeta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='targetas',
            name='duenno',
        ),
        migrations.AddField(
            model_name='targetas',
            name='duenno',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
