# Generated by Django 4.2.5 on 2023-11-18 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_targetas_duenno_targetas_duenno'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
