# Generated by Django 4.2.5 on 2023-11-18 03:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket', '0002_alter_ticket_destino_alter_ticket_origen'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='numero_ticket',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='ticket',
            name='reservado_por',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_status',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Reservado', 'Reservado'), ('Cerrado', 'Cerrado')], default='Activo', max_length=15),
        ),
    ]
