# Generated by Django 4.2.5 on 2023-11-18 03:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket', '0003_ticket_numero_ticket_ticket_reservado_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='reservado_por',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_status',
            field=models.CharField(choices=[('Reservado', 'Reservado'), ('Activo', 'Activo'), ('Cerrado', 'Cerrado')], default='Activo', max_length=15),
        ),
    ]
