# Generated by Django 4.2.5 on 2023-11-18 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_alter_ticket_reservado_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_status',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Reservado', 'Reservado'), ('Cerrado', 'Cerrado')], default='Activo', max_length=15),
        ),
    ]
