# Generated by Django 4.2.5 on 2023-11-18 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0006_alter_ticket_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_status',
            field=models.CharField(choices=[('Cerrado', 'Cerrado'), ('Reservado', 'Reservado'), ('Activo', 'Activo')], default='Activo', max_length=15),
        ),
    ]
