# Generated by Django 4.2.5 on 2023-11-18 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0009_alter_ticket_ticket_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='numero_ticket',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_status',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Reservado', 'Reservado'), ('Cerrado', 'Cerrado')], max_length=15),
        ),
    ]
