# Generated by Django 4.2.5 on 2023-11-18 03:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0010_remove_ticket_numero_ticket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='numero_ticket',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_status',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Cerrado', 'Cerrado'), ('Reservado', 'Reservado')], default='Activo', max_length=15),
        ),
    ]
