# Generated by Django 4.2.5 on 2023-11-18 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0014_alter_ticket_reservado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_status',
            field=models.CharField(choices=[('Reservado', 'Reservado'), ('Cerrado', 'Cerrado'), ('Activo', 'Activo')], default='Activo', max_length=15),
        ),
    ]
