# Generated by Django 4.2.5 on 2023-11-18 04:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0017_alter_ticket_reservado_por_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='id',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='numero_ticket',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_status',
            field=models.CharField(choices=[('Reservado', 'Reservado'), ('Activo', 'Activo'), ('Cerrado', 'Cerrado')], default='Activo', max_length=15),
        ),
    ]
